const User = require('../../models/users')

/**  TODO
 * 
 * SIGN-UP FUNCTIONALITY
 *  -- PULL WEBFLOWS API USER INFORMATION TO STORE THE DATA INTO MONGODB DATABASE
 *  -- NEED TO PASS A TOKEN THROUGH AS WELL AS ENCRYPT THE PASSWORD
 * 
 * 
 * LOGIN FUNCTIONALITY 
 *  -- RETRIEVE USER INFORMATION IF THERE IS A MATCHING EMAIL AND ID(MAYBE) IN DATABASE
 */